name: webview_flutter_web_example
description: Demonstrates how to use the webview_flutter_web plugin.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.0
  flutter_screen_recording: ^2.0.16
  cross_file: ^0.3.4+2
  flutter_webrtc: ^0.8.1
  cupertino_icons: ^1.0.2

flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  
