name: tatumoto_view
description: Chat Sample

version: 0.10.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  flutter_webrtc: ^0.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.2

dependency_overrides:
  intl: ^0.18.1
  uuid: ^3.0.7
  http: ^1.1.0
  web_socket_channel: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/img_not_available.jpg
  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
