name: webview_flutter_web_example
description: Demonstrates how to use the webview_flutter_web plugin.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4
  screenshot: ^3.0.0
  path_provider: ^2.1.4
  cross_file: ^0.3.4+2
  flutter_webrtc: ^0.6.4

flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  
