name: chat_sample
description: Chat Sample

version: 0.10.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectycube_sdk: ^2.12.0
  #  connectycube_sdk:
  #      path: ../../flutter-sdk
  shared_preferences: ^2.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.2

dependency_overrides:
  intl: ^0.18.1
  uuid: ^3.0.7
  http: ^1.1.0
  web_socket_channel: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/img_not_available.jpg
  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
