name: webview_flutter_web_example
description: Demonstrates how to use the webview_flutter_web plugin.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.0
  firebase_storage: ^11.1.0
  flutter_webrtc: ^0.8.0

  
  http: ^1.2.2
  shared_preferences: ^2.0.10 # Optional: For local storage
  cupertino_icons: ^1.0.2

flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  
