name: webview_flutter_web_example
description: Demonstrates how to use the webview_flutter_web plugin.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 適宜、適切なVersionを入れてください。
  cloud_firestore: ^4.8.0
  firebase_core: ^2.32.0
  screenshot: ^1.2.3
  
dev_dependencies:
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
